server:
  port: 7777
spring:
  application:
    name: spring-jpa
  #db mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kbdb
    username: master
    password: tiger
  servlet:
    multipart:
      max-file-size: 100MB # 파일 업로드 최대 용량 설정
      max-request-size: 1000MB # 요청 보낼때 파일 업로드 총 용량
  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update, 배포 운영시에는 none으로 권장
      show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: false
      org.hibernate.type: trace
file:
  upload_dir: D:/devSource/Spring/uploads #upload dir